# Site settings
author: Kyle Luke
title: Navigating Through the Flatirons
header-img: img/home-bg.png
email: th.oldschool@gmail.com
copyright_name: Kyle Luke
description: > # this means to ignore newlines until "baseurl:"
  Follow my trip through the Online Software Engineering Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lukekyl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
